### ISSUE TITLE
problem of lane detection

### ISSUE THREAD

**Issue by luckyjohnfeng** [hustvl/YOLOP#78]
Hello:

I use your default model weights, and default parameters.

I do not get a good lane detection as your demo.
<img width="1440" alt="problem of lane" src="https://user-images.githubusercontent.com/72537572/143973610-f05945ef-699b-4eb8-97ff-0561c8297930.png">

I am wondering is there any threshold I should set in the inference process or demo.py ?

Thank you very much in advance.

John Feng in Shanghai, China

**Comment by xiaoerjason** [comment]
我获得了和你一样的问题，请问你找到原因了吗？

**Comment by Riser6** [comment]
Helo! Thanks for your attention and support to our YOLOP project, this problem is  because of lane line post-processing（polynomial fitting). If you want to reproduce the demo effect at our github homepage, just comment out lines 128~129 in tools/demo.py.

你好，感谢你对YOLOP项目的关注和支持，你说的误检应该是车道线后处理（多项式拟合）的问题，如果想要获得我们github主页demo的效果，把source code中tools/demo.py 128~129行注释掉就可以了

**Comment by luckyjohnfeng** [comment]
感谢您的回复！ YOLOP的效果 目前来看还是比较好的，谢谢！
